services:
    purchase.manager:
        class: DefaultBundle\Service\PurchaseManager
        arguments: ['@swiftmailer.mailer', '@doctrine.orm.entity_manager', '@twig', '%email_from%', '%email_admin%']
    today.manager:
        class: DefaultBundle\Service\TodayManager
        public: true
        arguments: ['@doctrine.orm.entity_manager' ]
    panier.manager:
        class:  DefaultBundle\Service\PanierManager
        public: true
        arguments: ['@doctrine.orm.entity_manager']