<?php

namespace DefaultBundle\Repository;

/**
 * FreedomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreedomRepository extends \Doctrine\ORM\EntityRepository
{
}
