<?php

namespace DefaultBundle\Repository;

/**
 * GoingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoingRepository extends \Doctrine\ORM\EntityRepository
{
}
