<?php

namespace DefaultBundle\Repository;

/**
 * IntroductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntroductionRepository extends \Doctrine\ORM\EntityRepository
{
}
