<?php

namespace DefaultBundle\Repository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArrayIdPhoto($id){
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.id');
        $qb->where('a.serie = :id')
            ->setParameter('id', $id)
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
    public function findInfoBuyList($id){
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.id, a.code, a.price, a.ext, a.keyImg, a.name, a.title');
        $qb->where('a.id = :id')
            ->setParameter('id', $id)
        ;
        return $qb
            ->getQuery()
            ->getSingleResult()
            ;
    }
}
