<?php

namespace DefaultBundle\Repository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArrayIdSerie(){
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.id');
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
